from typing import List, NamedTuple

JT_SQUARE: int = ...
JT_ROUND: int = ...
JT_MITER: int = ...

ET_CLOSEDPOLYGON: int = ...
ET_CLOSEDLINE: int = ...
ET_OPENBUTT: int = ...
ET_OPENSQUARE: int = ...
ET_OPENROUND: int = ...

CT_INTERSECTION: int = ...
CT_UNION: int = ...
CT_DIFFERENCE: int = ...
CT_XOR: int = ...

PT_SUBJECT: int = ...
PT_CLIP: int = ...

PFT_EVENODD: int = ...
PFT_NONZERO: int = ...
PFT_POSITIVE: int = ...
PFT_NEGATIVE: int = ...

class PyPolyNode: ...

class PyIntRect(NamedTuple):
    left: ...
    top: ...
    right: ...
    bottom: ...

class ClipperException(Exception): ...

class Pyclipper:
    def AddPath(self, path, poly_type: int, closed: bool = True) -> bool: ...
    def AddPaths(self, paths, poly_type: int, closed: bool = True) -> bool: ...
    def Clear(self) -> None: ...
    def GetBounds(self) -> PyIntRect: ...
    def Execute(self, clip_type: int, subj_fill_type: int, clip_fill_type: int) -> List: ...

class PyclipperOffset:
    def AddPath(self, path, join_type: int, end_type: int) -> None: ...
    def AddPaths(self, paths, join_type: int, end_type: int) -> None: ...
    def Execute(self, delta: float) -> List: ...
    def Execute2(self, delta: float) -> PyPolyNode: ...
    def Clear(self) -> None: ...

class PyclipperOffsetEx:
    def AddPath(self, path, join_type: int, end_type: int) -> None: ...
    def AddPaths(self, paths, join_type: int, end_type: int) -> None: ...
    def Execute(
        self, ldelta: float, rdelata: float, tdelta: float, bdelta: float, sdelta: float
    ) -> List: ...
    def Clear(self) -> None: ...

def Orientation(poly: List) -> bool: ...

def Area(poly: List) -> float: ...
